### ISSUE TITLE
diskless mining howto

### ISSUE THREAD

**Issue by skoto** [easycryptomining/ecm#1]
hey

loved your crypto diskless mining howto...it is something I would like todo.

Have a question though - instead of using ubuntu in the node and installing drivers, etc. could I just have the server serve up a simple miner OS image, Hive OS image, or even boot a Windows image?

I don't mind using Ubuntu for a node, but if I could use SMOS/Hive/Windows, that would be cool.

I'm not a bit fan with mining in Windows, but I have been using the Awesome Miner program which automining of the most profitable coin with autoconvert to Bitcoin, so might want to run it on a couple of nodes.

**Comment by easycryptomining** [comment]
Hello,

Sorry for the late answer, i was not watching my own repo ^^

A PXE server can serve ISO file directly ("pxe boot iso" in google will help you). As far as i've tried it in the past, it'll work fine with small Linux based iso. The iso is loaded in the node RAM then run from it so you'll need more RAM on the node.

For Windows, sorry i'm not interested in this so can't help you.
